### ISSUE TITLE
Installer Confusion

### ISSUE THREAD

**Issue by HyperMan19680** [ThexXTURBOXx/Reforged#135]
I just got the Reforged Installer that was offered on CurseForge, and I am confused on how exactly to set it up. Do I just find my .minecraft folder and press the "Install for 1.8.9" Button? Or is there something else I need to know about?

**Comment by ThexXTURBOXx** [comment]
Ok, a little tutorial ^^
1. Find your .minecraft-folder (You have to select it, because the installer should be compatible with MultiMC) and select it.
2. Select the desired version of Reforged to install (the latest one is selected by default).
3. You can view the Changelog, if you want to.
4. If you want to install one or both addons, then just select them.
5. Click either on "Install for 1.8" or "Install for 1.8.9". This depends on your Minecraft-version you want to use.
6. You can change the path to the .minecraft-folder later on, if you need to or you want.
7. If you want to remove Reforged or its addons, then press on the "Manage Reforged-Versions"-button and you see a list with all installed versions of Reforged and its addons. You can either remove the version, that is selected in the list by clicking "Delete selected version" or you can remove all installed versions by clicking on "Delete all installed versions".

I hope, that this helps ^^

P.S.: There is a little [EULA](https://github.com/ThexXTURBOXx/thexxturboxx.github.io/blob/master/README.md) for the Installer. If you just use our installer as a normal user, you don't even have to read it... We only created it, that noone can steal our code or blame us for creating some files on your PC (the files are listed in the EULA).

**Comment by darkphan** [comment]
This breaks installing the mod via the Curse Voice launcher.

**Comment by ThexXTURBOXx** [comment]
Ok, that's bad... You can't install Beta-versions then?

**Comment by darkphan** [comment]
This is what now shows up, and you can not go back to older versions from what I see:

[screenshot](http://puu.sh/nPfKQ/7af374b383.png)

**Comment by ThexXTURBOXx** [comment]
Hmmm... Ok, either we will release a new version the next days or i will try to include the installer in the mod-jar...

**Comment by ThexXTURBOXx** [comment]
If I include the installer in the mod-jar, everything seems to work perfectly, but the file-size is TOO big... I think, we will release a hotfix or something like that in the next days.

**Comment by ThexXTURBOXx** [comment]
I found out how to install the right versions:
1. Uninstall the ReforgedInstaller.jar XD
2. Press on Add Mods
3. Search for our mod (Reforged)
4. Press on Reforged (not on install)
5. Go to versions
6. Install the preferred version (next to it on the right side is a little "Install-button")

**Comment by darkphan** [comment]
Thanks. Would be handy if they had a way to select which version if the mod is already installed. Are you guys going to move the Installer to it's own file, or how are updates going to happen in the future. Right now I just have to make sure I do not install the update in my pack.

**Comment by ThexXTURBOXx** [comment]
We just let the 1 file of the installer there (on CurseForge). The updates of the Installer will be hosted [here](http://thexxturboxx.github.io/). You also get notificated about Installer updates by the Installer itself. A mod-update-checker is not planned right now, but maybe later on (for now use Dynious's Version Checker mod, we support that one!)

**Comment by ThexXTURBOXx** [comment]
And I think I close this for now (if no further problems exist)
