### ISSUE TITLE
Rearrange the order of files on curse to the following

### ISSUE THREAD

**Issue by Sunconure11** [ThexXTURBOXx/Reforged#136]
Jar files should be uploaded last.

But first, compilation files, and installers should be uploaded first. That way, curse can pick up on only the jar file, and thus, allow users to update it via the launcher without issues, and if they want to use installers or compilation files, they would have to go to the site for that.

Also, I suggest allowing for manual installation as well. The installer is currently very buggy.

**Comment by ThexXTURBOXx** [comment]
I don't find any bugs in the installer... We will upload a new version for our mod, so that the CurseVoice-bug gets fixed...
P.S.: Yeah, it was a mistake by me to upload the Installer first and then the mod-jar (We won't upload any updates of the installer to CurseForge, only the first version will remain there)
