### ISSUE TITLE
Implement Reach

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [ThexXTURBOXx/Reforged#85]
Find out what is necessary to explain the concept of weapon range to Minecraft and use that for spears, halberds, etc.

**Comment by Domochevsky** [comment]
Hm, having done a bit of searching myself... **attackTargetEntityWithCurrentItem** exists in **EntityPlayer**, which calls the attack, damage, crits and such, when an entity was attacked. I'm not seeing any range indications there, so that must be somewhere higher.

That function is called by **PlayerControllerMP**, under **attackEntity**, which seems to be another layer of abstraction, sending out an attack packet and syncing the item.

That function is called by... **func_147116_af** (obfuscated) in the main **Minecraft** class. It seems to restrict left clicks to every 10 ticks, to avoid overly heavy spamming. It references _this.objectMouseOver_, which is a MovingObjectPosition, containing the block or entity that was hit by a ray trace. No range indication here either, however. 

I suspect following that field will have more info how that is filled...

...that field gets filled by **getMouseOver** in **EntityRenderer** via
_this.mc.objectMouseOver = this.mc.renderViewEntity.rayTrace(d0, p_78473_1_);_

rayTrace takes 2 arguments, distance and something called "partialTickTime". This looks relevant.
Distance is defined one line higher via 
_double d0 = (double)this.mc.playerController.getBlockReachDistance();_

Which is an instance of PlayerControllerMP and returns fixed values of
_this.currentGameType.isCreative() ? 5.0F : 4.5F;_

So 5 blocks in creative mode and 4.5 blocks outside.
4.5 blocks seems high... maybe that's minus the block the player is on? The raytrace seems to go by block coords.

So knowing this... this thing sits pretty much at the core. Maybe write a left-click event listener that does your own raytrace when someone swings their spear, with more range applied and then go by that? I could see that working. (I did that semi-successfully myself, come to think of it.)

**Comment by ThexXTURBOXx** [comment]
Wow, you guy rock! ^^

**Comment by Domochevsky** [comment]
It seemed relevant to my interests. :D

(I'm the author of QuiverBow, which operates in a similar (but ranged) field of mods.)

**Comment by ThexXTURBOXx** [comment]
Oh, this mod ^^
I liked it (I played much with it before I began to code mods :D )

**Comment by TheOnlySilverClaw** [comment]
Yep, thanks. It might spare me from digging through all of that myself. :)

**Comment by ThexXTURBOXx** [comment]
Added in 63c91de3c60ef4a465ea13a64e983be688e063a0
